/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GRAFICO;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;


//Importar Log
import org.apache.log4j.Logger;

//JSoup
import org.jsoup.Jsoup;
import org.jsoup.Connection;
import org.jsoup.Connection.Response;

/**
 *
 * @author ManuReyesI
 */
public class Grafico_Con extends javax.swing.JDialog {

    private static Logger log = Logger.getLogger(Grafico_Con.class);
    
    /**
     * Creates new form Grafico_Con
     */
    public Grafico_Con(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Nombre Ventana
        this.setTitle("Configuracion");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_User = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto_usuario = new javax.swing.JTextPane();
        Label_Pass = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        texto_contrasena = new javax.swing.JTextPane();
        Label_Pass1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto_host = new javax.swing.JTextPane();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        errores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Label_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/userpequeno.png"))); // NOI18N

        texto_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        texto_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(texto_usuario);

        Label_Pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/passpequeno.png"))); // NOI18N

        texto_contrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        texto_contrasena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane4.setViewportView(texto_contrasena);

        Label_Pass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ico_dns.png"))); // NOI18N

        texto_host.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        texto_host.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane3.setViewportView(texto_host);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        errores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_User)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Pass)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_Pass1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Label_User, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_Pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed

        log.info("Pulsando btn Aceptar");

        if(texto_usuario.getText().isEmpty() || texto_contrasena.getText().isEmpty() || texto_host.getText().isEmpty()){
            log.error("Campos incompletos");
            this.errores.setText("Campos Incompletos");
        }
        else{
            this.errores.setText("");
            log.info("Grabando datos en Clase de Credenciales");
            
            String[] auxHost = this.texto_host.getText().split("\\.");
            
            //Comprobar IP host
            boolean errorBuscarHost = false;
            try{
                log.info("Preparandose para buscar IP de host " + this.texto_host.getText());
                InetAddress dirIp = InetAddress.getByName(this.texto_host.getText());
            }
            catch(UnknownHostException ex){
                log.error("Error al buscar IP de Host "+ this.texto_host.getText());
                errorBuscarHost = true;
            }
            
            if(auxHost.length != 3){
                log.error("Error el nombre de Host");
                this.errores.setText("Error en el nombre de Host");
            }
            else if(errorBuscarHost){
                log.error("El host "+this.texto_host.getText()+" no existe");
                this.errores.setText("El host no existe");
            }
            else{

                String dominio = auxHost[1]+"."+auxHost[2];
                String host = auxHost[0];
                String ip = "";
                
                boolean error = false;
                
                //Buscar IP
                try{
                    log.info("Preparandose para buscar IP de host " + this.texto_host.getText());
                    InetAddress dirIp = InetAddress.getByName(this.texto_host.getText());
                    ip = dirIp.getHostAddress().toString();
                }
                catch(UnknownHostException ex){
                    log.error("Error al buscar IP de Host "+ this.texto_host.getText());
                    error = true;
                }
                
                //Probar conexion
                try{
                    log.info("Preparando Inicio de Sesion");
                    
                    UTILES.Credenciales credenciales = new UTILES.Credenciales();
                    
                    Response response = Jsoup.connect(credenciales.URL+"/login").method(Connection.Method.POST)
                            .data("id", this.texto_usuario.getText())
                            .data("password", this.texto_contrasena.getText())
                            .data("recordar", "0")
                            .execute();
                    
                    //log.info(response.body().toString());
                    
                    String cadenaError = "validation-error";
                    
                    if(cadenaError.indexOf(response.body()) != -1){
                        error = true;
                        log.error("Error al iniciar sesion, datos incorrectos");
                    }
                    
                }
                catch(IOException ex){
                    error = true;
                    log.error("Error al iniciar Sesion");
                }
                
                if(error){
                    this.errores.setText("Error al iniciar sesion");
                }
                else{
                    log.info("Introduciendo datos en Credenciales");
                    Grafico_Principal.credenciales(this.texto_usuario.getText(), this.texto_contrasena.getText(), dominio, host, ip);
                    this.setVisible(false);
                }
            }
        }

    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed
    
    @Override
    public void dispose() {
        log.info("Preparandose para cerrar Ventana de Configuracion");
        
        // Cerrar ventana
        super.dispose();
        System.exit(0);
        
        //Llamar cierre ventana
        Grafico_Principal.cerrarSinGuardar();        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico_Con.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico_Con.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico_Con.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico_Con.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Grafico_Con dialog = new Grafico_Con(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Pass;
    private javax.swing.JLabel Label_Pass1;
    private javax.swing.JLabel Label_User;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel errores;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane texto_contrasena;
    private javax.swing.JTextPane texto_host;
    private javax.swing.JTextPane texto_usuario;
    // End of variables declaration//GEN-END:variables
}
